Update utils.jl
FourierFlows/FourierFlows.jl pull request #318
Opened 2022-05-28 21:56 UTC by parfenyev

Fixing bug in the function `radialspectrum()`.  Now the definitions of `lshift` and `kshift` are consistent with the operation `fftshift`.

2022-05-28 22:56 UTC, navidcy requested changes
I suggested using the grid's wavenumber and shifting them using `FFTW.fftshift` instead of re-creating them. This way we minimize the places where errors can be introduced.

Also, I'd suggest changing

```julia
kshift = range(0, stop=grid.nkr-1, length=grid.nkr) * 2π/grid.Lx
```

to

```julia
kshift = grid.kr
```

2022-05-28 22:56 UTC, navidcy commented on src/utils.jl
> +  lshift = range(-grid.nl/2, stop=grid.nl/2-1, length=grid.nl) * 2π/grid.Ly
```suggestion
  lshift = fftshift(grid.l)
```

2022-05-28 22:56 UTC, navidcy commented on src/utils.jl
> +    kshift = range(-grid.nk/2, stop=grid.nk/2-1, length=grid.nk) * 2π/grid.Lx
```suggestion
    kshift = fftshift(grid.k)
```

2022-05-28 23:00 UTC, navidcy commented
You'd probably need to import `fftshift`, e.g., add it in

https://github.com/parfenyev/FourierFlows.jl/blob/ebeb30c9fed132a97e3bf19870ccd3f18290dc15/src/FourierFlows.jl#L77

2022-05-29 07:52 UTC, parfenyev commented
In your version I have the problem with interpolation:
```
MethodError: no method matching scale(::Interpolations.BSplineInterpolation{ComplexF64, 2, Matrix{ComplexF64}, BSpline{Linear{Throw{OnGrid}}}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::Matrix{Float64}, ::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64})
Closest candidates are:
  scale(::AbstractInterpolation{T, N, IT}, ::AbstractRange...) where {T, N, IT} at ~/.julia/packages/Interpolations/y4lLj/src/scaling/scaling.jl:27
```

2022-05-29 08:19 UTC, navidcy commented
Yeap, fair. Forget my suggestion then! :)

2022-05-29 08:20 UTC, navidcy approved these changes

2022-05-29 08:20 UTC, navidcy commented
Thanks @parfenyev!

2022-05-29 08:20 UTC, merged